obj-y += init.o cmdline.o machtype.o setup.o irq.o early_printk.o time.o reset.o  cop2-ex.o

obj-$(CONFIG_SMP) += smp.o

obj-$(CONFIG_SWIOTLB) += swiotlb.o

obj-$(CONFIG_LOONGSON_HPET) += hpet.o
obj-$(CONFIG_PCI_MSI) += pci_msi.o
obj-$(CONFIG_PM) += pm.o sleep.o
